[package]
name = "gap_query_interval_tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-new = "0.5.9"
discrete_range_map = "0.4.1"
serde = "1.0.164"
