[package]
name = "gap_query_interval_tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
discrete_range_map = { path = "../discrete_range_map" }
itertools = "0.10.5"
serde = "1.0.164"
