name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Mirror and run GitLab CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: "https://gitlab.com/ripytide/gap_query_interval_tree"
        env:
          FOLLOW_TAGS: "true"
          FORCE_PUSH: "false"
          GITLAB_HOSTNAME: "gitlab.com"
          GITLAB_USERNAME: "ripytide"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: "52730280"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
